apiVersion: v1
kind: Service
metadata:
    name: fritzgdockerdjangowebapplinux
spec:
    type: LoadBalancer
    ports:
    - port: 2222 
    selector:
        app: fritzgdockerdjangowebapplinux